# Generated by Django 5.0.7 on 2024-08-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_aurthor_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aurthor',
            name='published_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
