# Generated by Django 5.0.7 on 2024-08-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_aurthor_published_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aurthor',
        ),
    ]
