# Generated by Django 4.2.14 on 2024-08-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hashTagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
