# Generated by Django 4.2.14 on 2024-08-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_hashtagsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonBlogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
