# Generated by Django 4.2.14 on 2024-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_pythonblogsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_info', models.TextField()),
            ],
        ),
    ]
