# Generated by Django 4.2.14 on 2024-08-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_topicmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicmodel',
            old_name='topic_info',
            new_name='content',
        ),
    ]
