# Generated by Django 4.2.14 on 2025-01-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0010_htmlblogsmodel_htmltopicmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSSBlogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CSSTopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
